# Generated by Django 2.2.3 on 2019-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.FileField(upload_to='upload/')),
                ('chapter', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('thumnail', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
